#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [[ -z "$SCENARIO_NAME" ]]; then
    source "$DIR/ubuntu-settings"
fi

molecule lint -s $MOLECULE_SCENARIO \
 && molecule converge -s $MOLECULE_SCENARIO \
 && molecule idempotence -s $MOLECULE_SCENARIO \
 && molecule verify -s $MOLECULE_SCENARIO
