#!/bin/bash

if [[ -z "$SCENARIO_NAME" ]]; then
    source ./ubuntu-settings
fi

molecule lint -s $MOLECULE_SCENARIO \
 && molecule converge -s $MOLECULE_SCENARIO \
 && molecule idempotence -s $MOLECULE_SCENARIO \
 && molecule verify -s $MOLECULE_SCENARIO
