---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  ansible-lint molecule/resources/playbooks/converge.yml
  flake8
platforms:
  - name: "ansible-yubikey_${MOLECULE_DISTRIBUTION:-ubuntu18}"
    image: "${MOLECULE_IMAGE:-quay.io/samdoran/ubuntu18-ansible}"
    dockerfile: ../resources/playbooks/Dockerfile.j2
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    pre_build_image: false
provisioner:
  name: ansible
  options:
    vvv: true
  playbooks:
    converge: ../resources/playbooks/converge.yml
scenario:
  name: {{ cookiecutter.podman_scenario_name }}
verifier:
  name: testinfra
  directory: ../resources/tests/
  options:
    verbose: true
